/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2729e704099324a005f89a3c01f604ee)
interface __BaseEnv_Env {
	EMAIL_GATE_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/email-gate/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
