/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 54acb6b84c62e55933465dcf5b618905)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/email-gate/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
