import type { NormalizedFormalPalette } from "./formal-palette.types.ts";

// TEST ONLY / NON-PRODUCTION. Hashes and records are synthetic and do not
// represent the formal source workbook or a production-approved Palette.
export const TEST_ONLY_NON_PRODUCTION_FORMAL_PALETTE_FIXTURE = {
  manifest: {
    schemaVersion: "test-source-model-v1",
    paletteId: "poparooz-test-only",
    paletteVersion: "test-non-production",
    brand: "Poparooz",
    referenceSystem: "POPAROOZ",
    recordCount: 4,
    seriesOrder: ["A", "B", "C", "D", "E", "F", "G", "H", "M"],
    sourceFileName: "TEST-ONLY-NON-PRODUCTION.txt",
    sourceFileSha256: "a".repeat(64),
    canonicalRecordsSha256: "b".repeat(64),
    digitalColorPolicy: "source_declared",
    physicalColorPolicy: "unverified",
    displayNamePolicy: "optional_approved_only",
    status: "draft",
    createdAt: "2026-08-03T00:00:00Z",
  },
  colors: [
    {
      code: "A1",
      series: "A",
      seriesNumber: 1,
      seriesRank: 0,
      canonicalSourceIndex: 0,
      hex: "#FF0000",
      displayNameStatus: "not_provided",
      digitalColorStatus: "source_declared",
      physicalColorStatus: "unverified",
      sourceLocation: { sheet: "TEST ONLY", row: 2, column: 1 },
    },
    {
      code: "A2",
      series: "A",
      seriesNumber: 2,
      seriesRank: 0,
      canonicalSourceIndex: 1,
      hex: "#00FF00",
      displayName: "Test Green",
      displayNameStatus: "approved",
      digitalColorStatus: "source_declared",
      physicalColorStatus: "unverified",
      sourceLocation: { sheet: "TEST ONLY", row: 3, column: 1 },
    },
    {
      code: "B1",
      series: "B",
      seriesNumber: 1,
      seriesRank: 1,
      canonicalSourceIndex: 2,
      hex: "#0000FF",
      displayNameStatus: "not_provided",
      digitalColorStatus: "source_declared",
      physicalColorStatus: "unverified",
      sourceLocation: { sheet: "TEST ONLY", row: 4, column: 1 },
    },
    {
      code: "M1",
      series: "M",
      seriesNumber: 1,
      seriesRank: 8,
      canonicalSourceIndex: 3,
      hex: "#FFFFFF",
      displayNameStatus: "not_provided",
      digitalColorStatus: "source_declared",
      physicalColorStatus: "unverified",
      sourceLocation: { sheet: "TEST ONLY", row: 5, column: 1 },
    },
  ],
} as const satisfies NormalizedFormalPalette;
