export const SAFE_APPLICATION_BOOTSTRAP_ERROR_CODES = [
  "APPLICATION_RUNTIME_PALETTE_INVALID",
  "APPLICATION_BOARD_PROFILE_INVALID",
  "APPLICATION_COLOR_SET_INVALID",
  "APPLICATION_PROCESSING_POLICY_INVALID",
  "APPLICATION_GENERATION_RUNTIME_UNAVAILABLE",
  "APPLICATION_RUNTIME_INITIALIZATION_FAILED",
] as const;

export type SafeApplicationBootstrapErrorCode =
  (typeof SAFE_APPLICATION_BOOTSTRAP_ERROR_CODES)[number];
