export const SAFE_APPLICATION_BOOTSTRAP_ERROR_CODES = [
  "APPLICATION_RUNTIME_PALETTE_INVALID",
  "APPLICATION_BOARD_PROFILE_INVALID",
  "APPLICATION_RUNTIME_INITIALIZATION_FAILED",
] as const;

export type SafeApplicationBootstrapErrorCode =
  (typeof SAFE_APPLICATION_BOOTSTRAP_ERROR_CODES)[number];
